version: '3.8'

services:

  postgres-14:
    image: postgres:14.5
    restart: always
    expose:
      - 5432
    env_file:
      - ./.env
    volumes:
      - ./init_user_db.sql:/docker-entrypoint-initdb.d/init_user_db.sql

  cache:
    image: redis:6.2-alpine
    restart: always
    expose:
      - 6379


  web-server:
    build: .
    command: bash -c "cd /code && alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8080"
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - postgres-14
      - cache

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web-server
    ports:
      - "80:80"